FROM golang:latest AS build-stage

WORKDIR /app

COPY go.sum go.mod ./

RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /tests

# Run the test in the container
FROM build-stage AS run-test-stage
RUN go test -v ./...

# Deploying the application binary in lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /tests /tests

EXPOSE 5001

USER nonroot:nonroot

ENTRYPOINT [ "/tests" ]
